package chronicler
// Auto-generated from polyrepo's master-dependencies.json. Update via polyrepo dep-add and polyrepo dep-upgrade.
object Dependencies {
  val awsKinesis = "software.amazon.kinesis:amazon-kinesis-client:2.2.11"
  val awsKinesisProducer = "com.amazonaws:amazon-kinesis-producer:0.14.6"
  val awsSts2 = "software.amazon.awssdk:sts:2.17.73"
  val clikt = "com.github.ajalt.clikt:clikt:3.2.0"
  val jacksonDatabind = "com.fasterxml.jackson.core:jackson-databind:2.12.4"
  val jacksonDataformatYaml = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.12.4"
  val jacksonJsr310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.4"
  val jacksonKotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.12.4"
  val junitApi = "org.junit.jupiter:junit-jupiter-api:5.8.0-M1"
  val junitEngine = "org.junit.jupiter:junit-jupiter-engine:5.8.0-M1"
  val junitGradlePlugin = "org.junit.platform:junit-platform-gradle-plugin:1.2.0"
  val kotlinGradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0"
  val kotlinReflection = "org.jetbrains.kotlin:kotlin-reflect:1.6.0"
  val kotlinStdLibJdk8 = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.0"
  val kotlinTest = "org.jetbrains.kotlin:kotlin-test:1.6.0"
  val kotlinxCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2"
  val kotlinxCoroutinesDebug = "org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.5.2"
  val kotlinxCoroutinesJdk8 = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.5.2"
  val ktlintVersion = "0.40.0"
  val log4j = "org.apache.logging.log4j:log4j-1.2-api:2.14.0"
  val logbackClassic = "ch.qos.logback:logback-classic:1.2.5"
  val logstashLogbackEncoder = "net.logstash.logback:logstash-logback-encoder:6.6"
  val metricsCore = "io.dropwizard.metrics:metrics-core:4.0.2"
  val mockk = "io.mockk:mockk:1.12.0"
  val mysql = "mysql:mysql-connector-java:8.0.26"
  val nettyTcNative = "io.netty:netty-tcnative-boringssl-static:2.0.44.Final"
  val prometheusClient = "io.prometheus:simpleclient:0.9.0"
  val prometheusDropwizard = "io.prometheus:simpleclient_dropwizard:0.8.1"
  val prometheusHotspot = "io.prometheus:simpleclient_hotspot:0.8.1"
  val prometheusHttpserver = "io.prometheus:simpleclient_httpserver:0.8.1"
  val shadowJarPlugin = "gradle.plugin.com.github.johnrengelman:shadow:7.1.0"
  val vertxKotlinCoroutines = "io.vertx:vertx-lang-kotlin-coroutines:4.0.3"
  val vertxMysqlClient = "io.vertx:vertx-mysql-client:4.1.0"
  val wireGradlePlugin = "com.squareup.wire:wire-gradle-plugin:4.0.0-alpha.12"
  val wireRuntime = "com.squareup.wire:wire-runtime:4.0.0-alpha.19"
}
// Auto-generated from polyrepo's master-dependencies.json. Update via polyrepo dep-add and polyrepo dep-upgrade.
