name: Test

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 11

      - name: Test
        run: ./gradlew build --full-stacktrace --info
